### ISSUE TITLE
Hook failure during relation-departed hook

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/interface-http#18]
I got a hook error with a deployment of kubernetes-core from edge, after removing a relation that uses the http interface:

```
juju remove-relation kubernetes-worker kubernetes-master:kube-api-endpoint
```

Here's the error:

```
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-kubernetes-worker-0/.venv/lib/python3.6/site-packages/charms/reactive/__init__.py", line 73, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-kubernetes-worker-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-kubernetes-worker-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-kubernetes-worker-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-kubernetes-worker-0/charm/reactive/kubernetes_worker.py", line 475, in watch_for_changes
    servers = get_kube_api_servers(kube_api)
  File "/var/lib/juju/agents/unit-kubernetes-worker-0/charm/reactive/kubernetes_worker.py", line 912, in get_kube_api_servers
    for service in kube_api.services():
  File "/var/lib/juju/agents/unit-kubernetes-worker-0/charm/hooks/relations/http/requires.py", line 71, in services
    for h, pa, p in host_set]
UnboundLocalError: local variable 'service' referenced before assignment
```

I'm working on a fix.

**Comment by Cynerva** [comment]
Fix merged.
